In [1]:
import sys
sys.path.append("../")
import pandas as pd 
import numpy as np 
import os 
import misc

In [2]:
#frame = pd.read_csv("../dataset/LC_NSCLC_14_folders_20210203.csv", converters=misc.CONVERTERS)
frame_ori = pd.read_excel("../dataset/ct_pet_n_246/AIDATA_NSCLC+SCLC_20201130_tissue(n246)_필수예후인자(공대)_20210202수정.xlsx", converters=misc.CONVERTERS)
frame_ori

,PatientID,gender,age,Histology,Overall.stage,Clinical.T.Stage,Clinical.N.stage,Clinical.M.stage,Smoking.status,Smoking.amount,Deadstatus.event,Survival.time
0,LC00026,0.0,58.008219,1.0,4.0,4.0,1.0,0.0,1,3.0,1,34
1,LC00028,0.0,73.145205,1.0,4.0,1.0,2.0,0.0,1,25.0,1,74
2,LC00202,0.0,64.520548,1.0,6.0,2.0,2.0,1.0,0,0.0,1,195
3,LC00276,0.0,58.643836,1.0,5.0,2.0,3.0,0.0,1,40.0,1,829
4,LC00294,1.0,77.131507,0.0,6.0,1.0,3.0,2.0,0,0.0,1,170
...,...,...,...,...,...,...,...,...,...,...,...,...
241,LC10087,0.0,79.701370,NaN,NaN,NaN,NaN,NaN,1,40.0,1,134
242,LC10093,1.0,48.791781,0.0,6.0,5.0,2.0,1.0,0,0.0,9,585
243,LC21394,0.0,78.049315,1.0,6.0,3.0,2.0,2.0,1,30.0,9,114
244,LC22147,0.0,73.284932,NaN,NaN,NaN,NaN,NaN,1,50.0,1,27
245,LC23886,0.0,77.191781,NaN,NaN,NaN,NaN,NaN,1,60.0,9,12

In [16]:
frame = frame_ori.dropna()
frame = frame.set_index("PatientID")
frame = frame.reset_index("PatientID")
frame

,PatientID,gender,age,Histology,Overall.stage,Clinical.T.Stage,Clinical.N.stage,Clinical.M.stage,Smoking.status,Smoking.amount,Deadstatus.event,Survival.time
0,LC00026,0.0,58.008219,1.0,4.0,4.0,1.0,0.0,1,3.0,1,34
1,LC00028,0.0,73.145205,1.0,4.0,1.0,2.0,0.0,1,25.0,1,74
2,LC00202,0.0,64.520548,1.0,6.0,2.0,2.0,1.0,0,0.0,1,195
3,LC00276,0.0,58.643836,1.0,5.0,2.0,3.0,0.0,1,40.0,1,829
4,LC00294,1.0,77.131507,0.0,6.0,1.0,3.0,2.0,0,0.0,1,170
...,...,...,...,...,...,...,...,...,...,...,...,...
203,LC10075,1.0,53.249315,0.0,0.0,1.0,0.0,0.0,0,0.0,0,988
204,LC10077,1.0,76.956164,0.0,4.0,2.0,2.0,0.0,0,0.0,9,46
205,LC10084,1.0,58.794521,0.0,1.0,2.0,0.0,0.0,0,0.0,0,1050
206,LC10093,1.0,48.791781,0.0,6.0,5.0,2.0,1.0,0,0.0,9,585
207,LC21394,0.0,78.049315,1.0,6.0,3.0,2.0,2.0,1,30.0,9,114

In [17]:
histology = misc.to_categorical(frame["Histology"], 4)
gender = misc.to_categorical(frame["gender"], 2)
# overall = misc.to_categorical(frame["Overall.stage"], 7)
# t = misc.to_categorical(frame["Clinical.T.Stage"], 4)
# n = misc.to_categorical(frame["Clinical.N.stage"], 4)
# m = misc.to_categorical(frame["Clinical.M.stage"], 2)
# s = misc.to_categorical(frame["Smoking.status"], 2)

#data = np.concatenate((histology, gender, overall, t, n, m, s), axis=1)

data = np.concatenate((histology, gender), axis=1)

# histology.shape

In [18]:
# frame = frame.drop(["Mcode", "Mcode.description", 'gender', 'Histology', 'Overall.stage', 'Clinical.T.Stage', 
#                     'Clinical.N.stage', 'Clinical.M.stage', 'Overall.stage', 'Smoking.status'], axis=1)
frame = frame.drop(['gender', 'Histology'], axis=1)

In [19]:
frame_new = pd.concat([pd.DataFrame(data, columns=[str(i) for i in range(6)]), frame], axis=1)

patientID = np.unique(frame_new["PatientID"].astype(str))

frame_new = frame_new.set_index("PatientID")


frame_new = frame_new.replace({'Deadstatus.event': 9}, 0)



#frame_new = frame_new.dropna()

frame_new

,0,1,2,3,4,5,age,Overall.stage,Clinical.T.Stage,Clinical.N.stage,Clinical.M.stage,Smoking.status,Smoking.amount,Deadstatus.event,Survival.time
PatientID,,,,,,,,,,,,,,,
LC00026,0.0,1.0,0.0,0.0,1.0,0.0,58.008219,4.0,4.0,1.0,0.0,1,3.0,1,34
LC00028,0.0,1.0,0.0,0.0,1.0,0.0,73.145205,4.0,1.0,2.0,0.0,1,25.0,1,74
LC00202,0.0,1.0,0.0,0.0,1.0,0.0,64.520548,6.0,2.0,2.0,1.0,0,0.0,1,195
LC00276,0.0,1.0,0.0,0.0,1.0,0.0,58.643836,5.0,2.0,3.0,0.0,1,40.0,1,829
LC00294,1.0,0.0,0.0,0.0,0.0,1.0,77.131507,6.0,1.0,3.0,2.0,0,0.0,1,170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LC10075,1.0,0.0,0.0,0.0,0.0,1.0,53.249315,0.0,1.0,0.0,0.0,0,0.0,0,988
LC10077,1.0,0.0,0.0,0.0,0.0,1.0,76.956164,4.0,2.0,2.0,0.0,0,0.0,0,46
LC10084,1.0,0.0,0.0,0.0,0.0,1.0,58.794521,1.0,2.0,0.0,0.0,0,0.0,0,1050
LC10093,1.0,0.0,0.0,0.0,0.0,1.0,48.791781,6.0,5.0,2.0,1.0,0,0.0,0,585
LC21394,0.0,1.0,0.0,0.0,1.0,0.0,78.049315,6.0,3.0,2.0,2.0,1,30.0,0,114

In [20]:
frame_new = frame_new.reset_index()
frame_new

,PatientID,0,1,2,3,4,5,age,Overall.stage,Clinical.T.Stage,Clinical.N.stage,Clinical.M.stage,Smoking.status,Smoking.amount,Deadstatus.event,Survival.time
0,LC00026,0.0,1.0,0.0,0.0,1.0,0.0,58.008219,4.0,4.0,1.0,0.0,1,3.0,1,34
1,LC00028,0.0,1.0,0.0,0.0,1.0,0.0,73.145205,4.0,1.0,2.0,0.0,1,25.0,1,74
2,LC00202,0.0,1.0,0.0,0.0,1.0,0.0,64.520548,6.0,2.0,2.0,1.0,0,0.0,1,195
3,LC00276,0.0,1.0,0.0,0.0,1.0,0.0,58.643836,5.0,2.0,3.0,0.0,1,40.0,1,829
4,LC00294,1.0,0.0,0.0,0.0,0.0,1.0,77.131507,6.0,1.0,3.0,2.0,0,0.0,1,170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,LC10075,1.0,0.0,0.0,0.0,0.0,1.0,53.249315,0.0,1.0,0.0,0.0,0,0.0,0,988
204,LC10077,1.0,0.0,0.0,0.0,0.0,1.0,76.956164,4.0,2.0,2.0,0.0,0,0.0,0,46
205,LC10084,1.0,0.0,0.0,0.0,0.0,1.0,58.794521,1.0,2.0,0.0,0.0,0,0.0,0,1050
206,LC10093,1.0,0.0,0.0,0.0,0.0,1.0,48.791781,6.0,5.0,2.0,1.0,0,0.0,0,585
207,LC21394,0.0,1.0,0.0,0.0,1.0,0.0,78.049315,6.0,3.0,2.0,2.0,1,30.0,0,114

In [21]:
idx_wrong = np.where(frame_new['Survival.time'] == 0)[0]

#remove =  np.where(frame_new['Survival.time'] > 365*5)[0]

#remove = list(remove) + list(idx_wrong)

frame_new.drop(idx_wrong, inplace=True)

frame_new

,PatientID,0,1,2,3,4,5,age,Overall.stage,Clinical.T.Stage,Clinical.N.stage,Clinical.M.stage,Smoking.status,Smoking.amount,Deadstatus.event,Survival.time
0,LC00026,0.0,1.0,0.0,0.0,1.0,0.0,58.008219,4.0,4.0,1.0,0.0,1,3.0,1,34
1,LC00028,0.0,1.0,0.0,0.0,1.0,0.0,73.145205,4.0,1.0,2.0,0.0,1,25.0,1,74
2,LC00202,0.0,1.0,0.0,0.0,1.0,0.0,64.520548,6.0,2.0,2.0,1.0,0,0.0,1,195
3,LC00276,0.0,1.0,0.0,0.0,1.0,0.0,58.643836,5.0,2.0,3.0,0.0,1,40.0,1,829
4,LC00294,1.0,0.0,0.0,0.0,0.0,1.0,77.131507,6.0,1.0,3.0,2.0,0,0.0,1,170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,LC10075,1.0,0.0,0.0,0.0,0.0,1.0,53.249315,0.0,1.0,0.0,0.0,0,0.0,0,988
204,LC10077,1.0,0.0,0.0,0.0,0.0,1.0,76.956164,4.0,2.0,2.0,0.0,0,0.0,0,46
205,LC10084,1.0,0.0,0.0,0.0,0.0,1.0,58.794521,1.0,2.0,0.0,0.0,0,0.0,0,1050
206,LC10093,1.0,0.0,0.0,0.0,0.0,1.0,48.791781,6.0,5.0,2.0,1.0,0,0.0,0,585
207,LC21394,0.0,1.0,0.0,0.0,1.0,0.0,78.049315,6.0,3.0,2.0,2.0,1,30.0,0,114

In [22]:
for column in frame_new.columns:
    print(column, frame_new[column].isnull().values.any())

PatientID False
0 False
1 False
2 False
3 False
4 False
5 False
age False
Overall.stage False
Clinical.T.Stage False
Clinical.N.stage False
Clinical.M.stage False
Smoking.status False
Smoking.amount False
Deadstatus.event False
Survival.time False

In [23]:
frame_new.to_csv("../dataset/ct_pet_n_246/data_cleaned.csv", index=False)
len(frame_new)

208

In [11]:
frame_new.columns

Index(['index', '0', '1', '2', '3', '4', '5', 'age', 'Overall.stage',
       'Clinical.T.Stage', 'Clinical.N.stage', 'Clinical.M.stage',
       'Smoking.status', 'Smoking.amount', 'Deadstatus.event',
       'Survival.time'],
      dtype='object')

In [12]:
frame_new[frame_new.columns].isnull().values.any()

False

In [13]:
np.where(frame_new["Overall.stage"].isnull().values)

(array([], dtype=int64),)

In [14]:
early_stage_frame = frame_new.loc[frame_new['Overall.stage'] < 3]

# early_stage_frame.to_csv("../dataset/LungCNU_earlyStage/early_stage.csv", index=False)

In [15]:
latter_stage_frame = frame_new.loc[frame_new['Overall.stage'] >= 3]
# latter_stage_frame.to_csv("../dataset/LungCNU_latterStage/latter_stage.csv", index=False)